### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [RndMnkIII/PSP-SIO-port-IMU#1]
By using "PSP-SIO-port-IMU/MPU6050_2_teensy/I2C.ino" you have also include some unnecessary code.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

See also: https://github.com/Lauszus/BalancingRobotFullSize/issues/2

**Comment by RndMnkIII** [comment]
Thanks, but my intention is not to debug the functioning of third-party libraries on the Arduino side since this is more of a proof of concept and also seems to work correctly today (although it may not be the most efficient way). My intention is to migrate it to another type of microcontroller, preferably to an ESP32 with the development interface of Espressif and finally to the firmware of Micropython for ESP32 and not to get too involved in the Arduino environment itself. Right now my main interest is the development of an efficient communication protocol between the microcontroller and the PSP console for more complex future developments, since at the moment I do not know if it is possible or there is a way to read from the SIO port on the PSP console using interruptions or any other method that does not imply constant probing if there is data available to read from the serial port.
Thanks again for the suggestion to improve the code, which on the other hand are all welcome.
